version: '3.3'
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:6.0.0'
    hostname: zookeeper
    restart: unless-stopped
    expose:
      - 2181
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
#  kafka:
#    image: 'bitnami/kafka:latest'
#    hostname: kafka
#   restart: unless-stopped
#    ports:
#      - "9092:9092"
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ADVERTISED_HOST_NAME: kafka
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      ALLOW_PLAINTEXT_LISTENER: "yes"
#      KAFKA_CFG_LOG_RETENTION_MS: "1500"
#      KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS: "500"
