version: '3.3'
services:
    dp-cantabular-filter-flex-api:
        build:
            context: ../../../dp-cantabular-filter-flex-api
            dockerfile: Dockerfile.local
        command:
            - go 
            - test 
            - -cover 
            - -coverpkg=github.com/ONSdigital/dp-cantabular-filter-flex-api/... 
            - -component
        volumes:
            - ../../:/dp-cantabular-filter-flex-api
        depends_on:
            - kafka
        ports:
            - 27100:27100
        environment:
            BIND_ADDR:                          ":27100"
            SERVICE_AUTH_TOKEN:                 "testToken"
            COMPONENT_TEST_USE_LOG_FILE:        "${COMPONENT_TEST_USE_LOG_FILE-false}"
            KAFKA_ADDR:                         "kafka:9092"
            KAFKA_CONSUMER_MIN_BROKERS_HEALTHY: 1
            KAFKA_PRODUCER_MIN_BROKERS_HEALTHY: 1
            KAFKA_SEC_PROTO:                    ""
